### ISSUE TITLE
投稿を表示させる

### ISSUE THREAD

**Issue by yukikamome316** [fami-gb/simple-post-app#3]
## 概要
ページネーションを実装して、投稿をクライアントサイドで表示できるようにする。
実装はフレームワーク用いることなく、HTMLとCSS、JavaScirptのみを用いて行う。
ただし、細かいデザインなどは他のタスクで行うこととして、ここでは必要最低限の機能を実装する。

## 前提条件

- [x] #2

上記のタスクが完了していることを前提とする。

**Comment by fami-gb** [comment]
サーバー側でページネーション？を実装したことによってクライアント側でデータを受け取る際にかなり煩雑になってしまった気がします。
サーバー側のデータを一括で受け取る方法はあるのでしょうか。
現状サーバー側のデータを受け取る際は
`const response = fetch("http://localhost:8000/api/posts?page=1");`
のようにページ数を一々指定しなければなりません。

**Comment by yukikamome316** [comment]
> サーバー側のデータを一括で受け取る方法はあるのでしょうか。

@fami-gb 
全ての投稿を一括で取得しない実装をして欲しい
その`fetch`の方法で問題ないよ
